
server:
  port: 8001

spring:
  application:
    name: veterinarian_service
  datasource:
    url: jdbc:h2:mem:veterian
    username: sa
    password:
    schema: classpath*:hsqldb/schema.sql
    data: classpath*:hsqldb/data.sql
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
  h2:
    console:
      enabled: true
