
server:
  port: 8001

spring:
  application:
    name: veterinarian_service
  datasource:
    #url: jdbc:h2:mem:veterian
    #username: sa
    #password:
    url: jdbc:mysql://localhost/petclinic_ms_test
    username: root
    password: root1234
    schema: classpath*:hsqldb/schema.sql
    data: classpath*:hsqldb/data.sql
   # initialization-mode: always

  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
