---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: app_sources
- name: current-app-info

run:
  path: app_sources/ci/tasks/update-routes
