resources:
  - name: app_sources
    type: git
    source:
      uri: https://github.com/digital-pcf/pet_clinic_veterian_service.git
  - name: staging_deployment
    type: cf
    source:
      api: https://api.sys.dev.pcf-aws.com
      username: rajiv.uppal@wipro.com
      password: changeme
      organization: Pcf-training
      space: training
      skip_cert_check: false

jobs:
  - name: build
    public: true
    plan:
      - get: app_sources
        trigger: true
      - task: run-build
        config:
          platform: linux
          inputs:
            - name: app_sources
          image_resource:
            type: docker-image
            source:
              repository: maven
          run:
            path: sh
            args:
              - -exc
              - |
                echo "mvn Version"
                pwd
                cd app_sources
                mvn package
                mv target/veterinarian_service-0.0.1-SNAPSHOT.jar ../app_jar
                #mv manifest.yml ../app_jar
          outputs:
            - name: app_jar
      - put: staging_deployment
        params:
          path: app_jar/*.jar
          manifest: app_sources/manifest.yml